import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Script from "next/script";
import { useEffect, useRef, useState } from "react";
const smiles = "CC(=O)Oc1ccccc1C(=O)O";
export default function Home() {
  const [rdkit, setRDkit] = useState(null);
  const [molSvg, setMolSvg] = useState(null);
  const svgRef = useRef(null);
  useEffect(() => {
    console.log(rdkit);
    rdkit?.fn().then((RDKit) => {
      console.log(RDKit.version());
      const mol = RDKit.get_mol(smiles);
      const svg = mol.get_svg();
      setMolSvg(svg);
      if (svgRef) {
        svgRef.current = molSvg;
      }
    });
    console.log(window);
  }, [rdkit]);
  function createMarkup() {
    if (molSvg) return { __html: molSvg };
  }
  return (
    <div className={styles.container}>
      <Script
        src="https://unpkg.com/@rdkit/rdkit/Code/MinimalLib/dist/RDKit_minimal.js"
        onLoad={() => {
          setRDkit({ fn: window.initRDKitModule });
        }}
      ></Script>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {molSvg && <div dangerouslySetInnerHTML={createMarkup()}></div>}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
